/**
 * Local stack: Redis + Supabase CLI + prod public dump (HTTPS).
 *
 *   node scripts/stack.mjs redis|up|down|status|reset|dump|dump-schema|load|stamp|restore
 */
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  renameSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';
import {
  BOOTSTRAP_SCHEMA,
  PROD_PROJECT_REF,
  REMAP_SQL,
  SEED_AUTHOR_ID,
  SEED_IDS,
  SEED_PASSWORD,
  STAMP_IMAGE_LATEST,
} from './local-stack/constants.mjs';
import { dumpProdData } from './local-stack/dump-data.mjs';
import { loadProdData } from './local-stack/load-data.mjs';
import { dockerCompose, root, runCapture, supabase } from './local-stack/run.mjs';
import {
  BOOTSTRAP_SECTIONS,
  bootstrapMigrationName,
  groupBootstrapSections,
  isGeneratedBootstrap,
} from './local-stack/split-schema.mjs';
import {
  createStampImage,
  printStampStatus,
  restoreStampVolume,
  stampEnabled,
} from './local-stack/stamp.mjs';

const command = process.argv[2];

function ensureDocker() {
  const info = runCapture('docker', ['info']);
  if (info.status !== 0) {
    console.error(
      'Docker is not running. Start Docker Desktop, then retry. Local Supabase and Redis require Docker.'
    );
    process.exit(1);
  }
}

const PARKED_MIGRATIONS = 'supabase/.temp/parked-migrations';

function parkIncrementalMigrations() {
  const dir = join(root, 'supabase/migrations');
  const parked = join(root, PARKED_MIGRATIONS);
  mkdirSync(dir, { recursive: true });
  mkdirSync(parked, { recursive: true });
  for (const name of readdirSync(dir)) {
    if (!name.endsWith('.sql') || isGeneratedBootstrap(name)) continue;
    renameSync(join(dir, name), join(parked, name));
  }
}

function restoreIncrementalMigrations() {
  const dir = join(root, 'supabase/migrations');
  const parked = join(root, PARKED_MIGRATIONS);
  if (!existsSync(parked)) return;
  mkdirSync(dir, { recursive: true });
  for (const name of readdirSync(parked)) {
    renameSync(join(parked, name), join(dir, name));
  }
}

function withIsolatedMigrations(fn) {
  parkIncrementalMigrations();
  try {
    return fn();
  } finally {
    restoreIncrementalMigrations();
  }
}

function copyBootstrapMigration() {
  const src = join(root, BOOTSTRAP_SCHEMA);
  if (!existsSync(src)) {
    console.error(
      `Missing ${BOOTSTRAP_SCHEMA}. Ask the agent to dump public schema via MCP, or see supabase/bootstrap/README.md.`
    );
    process.exit(1);
  }
  const sql = readFileSync(src, 'utf8');
  if (
    !sql.includes('CREATE TABLE') ||
    !/public\.projects|TABLE public\.projects|TABLE "projects"/i.test(sql)
  ) {
    console.error(
      `${BOOTSTRAP_SCHEMA} does not look like a public schema dump. Ask the agent: dump public schema via MCP.`
    );
    process.exit(1);
  }
  const migrationsDir = join(root, 'supabase/migrations');
  mkdirSync(migrationsDir, { recursive: true });
  for (const name of readdirSync(migrationsDir)) {
    if (isGeneratedBootstrap(name)) unlinkSync(join(migrationsDir, name));
  }
  const grouped = groupBootstrapSections(sql);
  const written = [];
  BOOTSTRAP_SECTIONS.forEach((section, index) => {
    const stmts = grouped[section];
    if (!stmts?.length) return;
    const name = bootstrapMigrationName(section, index);
    const header = `-- Generated from ${BOOTSTRAP_SCHEMA} section ${section}. Do not edit.\n`;
    writeFileSync(join(migrationsDir, name), `${header}\n${stmts.join('\n\n')}\n`);
    written.push(`${name} (${stmts.length})`);
  });
  if (written.length === 0) {
    console.error(`${BOOTSTRAP_SCHEMA} produced no SQL sections.`);
    process.exit(1);
  }
  console.log(`Bootstrap migrations:\n  ${written.join('\n  ')}`);
}

function writeRemapSql() {
  const seedList = SEED_IDS.map((id) => `'${id}'::uuid`).join(', ');
  // Single statement: `supabase db query` cannot run multiple commands.
  const sql = `-- Generated by scripts/stack.mjs load — remaps leftover prod user FKs onto seed author.
DO $$
DECLARE
  rec record;
  author_id uuid := '${SEED_AUTHOR_ID}';
  seed_ids uuid[] := ARRAY[${seedList}];
BEGIN
  FOR rec IN
    SELECT DISTINCT
      tc.table_schema,
      tc.table_name,
      kcu.column_name
    FROM information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
      ON tc.constraint_name = kcu.constraint_name
      AND tc.table_schema = kcu.table_schema
    JOIN information_schema.constraint_column_usage AS ccu
      ON ccu.constraint_name = tc.constraint_name
      AND ccu.table_schema = tc.table_schema
    WHERE tc.constraint_type = 'FOREIGN KEY'
      AND tc.table_schema = 'public'
      AND tc.table_name <> 'profiles'
      AND (
        (ccu.table_schema = 'auth' AND ccu.table_name = 'users')
        OR (ccu.table_schema = 'public' AND ccu.table_name = 'profiles')
      )
  LOOP
    EXECUTE format(
      'UPDATE %I.%I SET %I = $1 WHERE %I IS NOT NULL AND %I <> ALL($2)',
      rec.table_schema,
      rec.table_name,
      rec.column_name,
      rec.column_name,
      rec.column_name
    )
    USING author_id, seed_ids;
  END LOOP;

  IF to_regclass('public.profiles') IS NOT NULL THEN
    DELETE FROM public.profiles WHERE id <> ALL(seed_ids);
  END IF;
END $$;
`;
  writeFileSync(join(root, REMAP_SQL), sql);
}

function printDumpSchemaHelp() {
  console.log(`Schema cannot be dumped with service_role keys (PostgREST has no DDL).

Ask the agent (MCP execute_sql):
  dump public schema via MCP into supabase/bootstrap/schema.sql

Fallback after \`npx supabase login\`:
  npx supabase link --project-ref ${PROD_PROJECT_REF}
  npx supabase db dump --linked -s public -f supabase/bootstrap/schema.sql

schema.sql is gitignored (local only). Never db push that dump to prod.
`);
}

function startSupabase() {
  copyBootstrapMigration();
  withIsolatedMigrations(() => supabase(['start']));
  supabase(['status', '-o', 'pretty']);
  printStampStatus();
}

const commands = {
  redis() {
    ensureDocker();
    dockerCompose(['up', '-d']);
  },
  async up() {
    ensureDocker();
    dockerCompose(['up', '-d']);
    if (stampEnabled()) {
      console.log(`Using ${STAMP_IMAGE_LATEST} (set STACK_STAMP=0 to bootstrap from schema.sql)`);
      restoreStampVolume();
    } else if (process.env.STACK_STAMP === '0' || process.env.STACK_STAMP === 'false') {
      console.log('STACK_STAMP=0 — bootstrap from schema.sql (stamp image ignored)');
    }
    startSupabase();
  },
  down() {
    ensureDocker();
    supabase(['stop']);
    dockerCompose(['down']);
  },
  status() {
    ensureDocker();
    dockerCompose(['ps']);
    supabase(['status', '-o', 'pretty']);
    printStampStatus();
  },
  reset() {
    ensureDocker();
    copyBootstrapMigration();
    withIsolatedMigrations(() => supabase(['db', 'reset', '--local', '--yes']));
  },
  'dump-schema'() {
    printDumpSchemaHelp();
  },
  async dump() {
    await dumpProdData();
  },
  async load() {
    ensureDocker();
    copyBootstrapMigration();
    withIsolatedMigrations(() => supabase(['db', 'reset', '--local', '--yes']));
    await loadProdData();
    writeRemapSql();
    console.log('Remapping leftover owner FKs onto seed author…');
    supabase(['db', 'query', '--local', '-f', join(root, REMAP_SQL)]);
    console.log(`Load complete. Log in as author@local.test / ${SEED_PASSWORD}`);
  },
  async stamp() {
    ensureDocker();
    await createStampImage();
    startSupabase();
    console.log(`Stamp complete. Daily use: npm run stack:up (restores ${STAMP_IMAGE_LATEST}).`);
  },
  restore() {
    ensureDocker();
    dockerCompose(['up', '-d']);
    restoreStampVolume();
    startSupabase();
  },
};

if (!command || !commands[command]) {
  console.error(
    'Usage: node scripts/stack.mjs <redis|up|down|status|reset|dump|dump-schema|load|stamp|restore>'
  );
  process.exit(1);
}

const result = commands[command]();
if (result && typeof result.then === 'function') {
  result.catch((err) => {
    console.error(err instanceof Error ? err.message : err);
    process.exit(1);
  });
}
